### PR TITLE
Fix undefined behavior with linkify when same url is repeated in same line

### PR DESCRIPTION
**Pull request by sujanadiga-practo**

### CODE REVIEW

**Comment by ralphbean** [comment]
It looks like this broke the test suite.  Can you have a look?

**Comment by sujanadiga-practo** [comment]
@ralphbean have fixed broken build, please review

**Comment by ralphbean** [comment]
Nice, thank you!  :)

**Comment by sujanadiga-practo** [comment]
@ralphbean Please create a release for this

**Pull request merged**
